name: Wbsite Workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASS }}
    - name: Build Docker image
      run: docker build -f ./Dockerfile -t myaccount/myapp .
    - name: Push Docker image to DockerHub
      run: docker push myaccount/myapp:latest
