name: Wbsite Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: desmond527/ciwebsite
        registry: docker.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASS}}
        
  restart_when_failed:
    name: Restarts the scheduled run when it failed
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && failure()
    steps:
      - name: Retry the workflow
        run: |
          curl -i \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" \
          https://api.github.com/repos/desmond527/CI_Website/actions/workflows/12559395/dispatches \
          -d '{"ref": "${{ github.ref }}" }'
        
