name: Wbsite Workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ secrets.ENV_USERNAME }}
        password: ${{ secrets.ENV_PASS }}
        
    - name: Build Docker image
      run: docker build -f ./Dockerfile -t desmond527/ciwebsite .
      
    - name: Push Docker image to DockerHub
      run: docker push desmond527/ciwebsite:latest
